### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Eoyie** [Aineopintojen-harjoitustyo-Algoritmit-j/miinaharava#1]
Annettu projekti ladattu: 14.2 noin klo. 12

Heti alkuun on myönnettävä, että koin kyseisen työn arvostelun hieman hankalaksi, sillä tähänhän on jo sinäänsä käytetty melkein koko odotettu kurssi aika. Minulla on siis mennyt enemmän aikaa yrittää keksiä mitään "vinkkejä" tai palautetta, kuin itse projektin tutustumiseen. En oikeastaan silti onnistunut keksimään mitään ja hieman pohdinkin, että miten tätä työtä pystyy vielä työstää n. 3-4 viikkoa? Annan siis enemmänkin pohdintoja projektiin liittyen, kuin mitään hyödyllisiä vinkkejä.

Kehitettävää?:
- Hieman pohdiskelin, miksi asennusohjeet ja linkki käyttöohjeisiin oli niin helposti saatavissa README:ssä, mutta ohjeet riippuvuuteen ym. olivat DEV.md tiedostossa? Kun en muutakaan moitittavaa keksi, niin ehkä näitä voisi siistiä? Ehkä invoke tyyppisiä taskeja voisi myös harkita, jolloin näitä pitkiä kommento rimpsuja esim. haarakattavuusraportille ei tarvitsisi kopioida vaan esim. voitaisiin vain kirjoittaa: `poetry run invoke coverage-report` ?
- En tiedä kuinka vaikea tämä olisi lisätä, mutta muistelin ja vielä varmistin, että normaalissa miinaharavassa ei yleisesti ensimmäisellä kerralla pysty osua heti miinaan. Ensimmäisenä tulisi mieleen, että pelillä ei olisi pelilautaa heti pelin alussa, vaan se luotaisiin vasta ensimmäisen valinnan jälkeen, jolloin tämä varmistettaisiin olevan jotain muuta, kuin miina. En tosin ymmärtänyt koodia niin hyvin, että osaisin heti sanoa, onko tämä järkevä muutos vai ei. Törmäsin tähän kuitenkin yllättävän usein testaillessani peliä.

Positiivista:
- Näitähän riittää, mutta ainakin ensimmäisenä yleisesti kaikki pdf:t ja -h osuudet olivat hyvin siistiä jälkeä ja helppoja ymmärtää.
- Mitä onnistuin koodista saamaan riti, niin vaikutti hyvin järkevältä ja toimivalta. Selvästi näki ensimmäisen viikon monen tunnin työt tämän eteen.

Yleisesti kaikki mitä testasin projektissa toimi, enkä törmännyt mihinkään ongelmiin. Siispä vertaisarvioinnin tekeminen tuntuikin hieman hassulta, koska työ tuntuu enemmän esimerkki työltä, kuin kurssin samassa vaiheessa olevalta työltä. Hyvää työtä, ei voi muuta sanoa.

**Comment by Aineopintojen-harjoitustyo-Algoritmit-j** [comment]
Kiitos oikein paljon hyvästä palautteesta. Tuo kehitystyökalujen ylipitkät rivit piti heti korjata. Saattaa olla, että jotkin miinaharavat toimivat kuten kuvaat ja tämä voisi olla ihan mukava optio. Pistetään sen toteutus harkintaan. Suljen nyt tämän issuen. Kiitos vielä ja oikein mukavaa kevättä!
