### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by PlatinumFoxTail** [Aineopintojen-harjoitustyo-Algoritmit-j/miinaharava#2]
## Yhteenveto

Kokonaisuudessaan vaikuttaa olevan hienosti dokumentoitu, toteutettu ja testattu ohjelma kaikille maailman miinaharava ratkasijoille :) Alla oleva vertaisarviointi tapahtunut 21.2 klo. 9:00-13:00 välillä.

### Ohjelman käytettävyys

- Käyttöohje selkeästi ja ytimekkäästi selitetty. Hyvää duunia!
- En saanut vaikeustaso -e toimimaan (ylös nuoli näppäin hakee terminaalin edellisiä komentoja), mutta johtunee siitä ettei 100merkkiä ei onnistu terminaalissani)
- Pieni mahdollinen parannusehdotus voisi olla jos -b < B > kirjoittaisi auki, että tarkoittaa -b 0, -b 1, -b 2? Minulle meni hetki hiffata.

### Rakenne yleisesti (__main__, cmdline, app, board, tui)

- Ylesesti seperation of concern näyttää tosi hyvältä esim. cmdline muuntaa komentorivin argumenteiksi.
- Koodi näyttää myös tosi hyvältä yleisesti esim. selkeät luokat ja metodien nimet kuvaavia.
- board.py:ssä ehkä voisi seuraavat asiat harkita kehitettäväksi:
    • collect_area: Saan käsityksen, että tämä palauttaa tyhjän yhteisen alueen. Siinä tapauksessa metodin nimi voisi ehkä olla esim. check_empty_area?
    • get_mask: Ymmärtääkseni mask on naamio englanniksi. Ehkä ruudut ovat enemmän hidden tai unrevealed ja metodin nimi voisi ehkä muuttaa sen mukaan?
    • flag: Tässä saan käsityksen, että on käytetty magic numbers. Ehkä voisi määrittää eksplisiittisesti sanallisesti mitä kukin arvo tarkoittaa kootusti ja käyttää sitä sanallista vakio koko koodissa?
- tui ehkä voisi sisältää joku virheilmoituksen tulostus jos käyttäjän syöte virheellinen esim. _Miinaharava -b <1>_ palauttaisi _Virheellinen syöte. Vivun -b:n kanssa ainoastaan vaihtoehdot -b 0, -b 1 ja -b 2 mahdollisia_

### Tekoäly yleisesti (bot.py, dssp.py, simple.py)

- Koska double set single point (DSSP) algoritimi oli minulle uusi algoritmi tuttavuus en voinnut arvioida algoritmin oikellisuutta tarkemmin tämän vertaisarvioinnin yhteydessä. En löytänyt dokumentaatiostasi yleiskuvaus DSSP:stä, joten ehkä sitä voisi lisätä esim. muutamia lauseita mitä algoritmi tekee ja millä yleisperiaatteell se toimii esim. Kohdasta 5.3 referenssistäsi https://dash.harvard.edu/handle/1/14398552
- metodi lucky_quess dssp.py tiedostossa vaikutti mielenkiintoiselta. Siellä ehkä voisi tarkentaa koodi kommentit hieman, mitä koodissa tapahtuu. Itse jäin pohtimaan, miksi arvotaan yksi kylmimmistä laatoista? Neuroverkkoitsta tuli vaan mieleen, että siellä koulutetaan mallia harjoitteludatalla ja mallia hyödynnetään sitten tuntematon datan arvioinnissa. Voisiko luoda joku “yleismiinakenttä” malli, josta “DSSP-extended” valitsee mikä kylmimmistä laadoista valitaan? Tuo arvonta jäi jotenkin itseäni häiritsemään :)

### Testit (test_app.py, test_board.py, test_bot.py, ykiskkötestit, testikattauvuusraportti, manuaalitestaus)
- test_board.py näyttää hyvin ja kattavasti toteuttuneelta. Hyvä duunia!
- test_app.py ja test_bot.py vaikuttaa myös hyvin tehtynä. Tuli mieleen olisiko hyvä vielä testata, että tekoäly valitsee oikeasta kylmien laatoiden joukosta jos on valittu, että tekoäly pitäisi valita satunnaisesti joku niistä?
- Yleisesti vaikuttaa tois kattavalta testattu! Manuaalitestaus oli myös hieno toteutus “puoliautomaattisesta testatuksesta”.
- Tuo ./dev.sh skripti oli uusi lähestymistapa itselleni ja kiva oppia semmoisesta lähestymistavasta. Ehkä voisi kirjoittaa README tiedostoon, että kuuluisi vaan kirjoittaa suoraan ./dev.sh terminaaliin. Tämän lisäksi jouduin ensiksi ajaa poetry install, ennen kun pystyin kokeilemaan skriptin eri toiminnot esim. ./dev.sh pytest, joten ehkä sitä voisi mainita README tiedostossa?
- Vaihtoehtoisesti voisi ajaa testit GitHub Actionina skriptin sijaan, niin saisi sitä automatisoitua joka kertaa kun pushaa gitiin.
- Muuten pytest, pylint jne. näyttää pelkkä vihreää.

**Comment by Aineopintojen-harjoitustyo-Algoritmit-j** [comment]
Hei!

Kiitos palautteesta! Tässähän oli paljon hyvää mietintää! Kaikesta en ole ihan samaa mieltä. mutta monet vinkit lähtee toteutukseen.

Näistä olen jopa eri mieltä:

Komentorivin vilreilmoitus komennolla `miinaharava -b <1>`:
Tässä siis kun ollaan suorittamassa komentoa komentotulkilla, niin merkit `<`, `>` ja `|` liittyy putkien käsittelyyn ja on siis komentotulkin tehtävä huoliehtiä niistä. `miinaharava -b '<1>'` antaa kyllä virheilmoituksen, mutta sekin voisi kieltämättä olla suomeksi. Ehkä vielä jonain päiväna opettelen gettextin ja .mo-tiedostot.

GHA:ssa on kyllä kaikki testit myöskin automatisoituna ja se käyttää myös tuota ./dev.sh:ta niiden ajamiseen.

Suljen tämän tästä nyt.

Kiitos vielä hyvistä vinkeistä ja mukavaa kevättä!!
